POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
	"email": "me@josebedoya.co",
	"password": "123456"
}

###

POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6Ikpvc2UiLCJsYXN0TmFtZSI6IkJlZG95YSIsImVtYWlsIjoibWVAam9zZWJlZG95YS5jbyIsImlhdCI6MTYwMDgwMjQ4MCwiZXhwIjoxNjAwODAyNTIwfQ.B-g-r-MEpdztWXrjJbnC5lMYus5f5QBoqyoFwKDvSpA"
}

###

GET http://localhost:3001/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJJZCI6MSwiZmlyc3ROYW1lIjoiSm9zZSIsImxhc3ROYW1lIjoiQmVkb3lhIiwiZW1haWwiOiJtZUBqb3NlYmVkb3lhLmNvIiwiaWF0IjoxNjAwODAyNDgwLCJleHAiOjE2MDA4MDI1MjB9LCJpYXQiOjE2MDA4MDI1MTAsImV4cCI6MTYwMDgwMjUzMH0.WmaT4gKEBovLdP33maAAUl4QWr_eE6T_ojP93wstNUg